# File: postgres-cluster.yaml
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: my-postgres-cluster
  namespace: postgres
spec:
  instances: 3                          # Number of replicas
  primaryUpdateStrategy: unsupervised

  # PostgreSQL Version
  postgresql:
    version: 14

  # Bootstrap Using Secret Only
  bootstrap:
    initdb:
      secret:
        name: my-postgres-secret       # Referencing Secret for DB Details Only

  # Storage Configuration
  storage:
    size: 10Gi
    storageClass: local-path
