apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app-image:latest
          ports:
            - containerPort: 3000

          # Inject all variables from secret
          envFrom:
            - secretRef:
                name: my-app-secret

          # Override specific variable using valueFrom or value
          env:
            - name: DB_NAME
              value: "radhika"  # Override secret value for DB_NAME
            - name: DB_USER
              value: "customuser"  # Optional: Manually change user
            - name: DEBUG_MODE
              value: "false"  # Disable debugging
