apiVersion: batch/v1
kind: Job
metadata:
  name: setup-job
spec:
  template:
    spec:
      containers:
        - name: setup
          image: your-backend-image:tag
          command: ["/bin/sh", "-c"]
          args:
            - |
              npm run setup:all && \
              npm run client
      restartPolicy: Never
  backoffLimit: 1
