# File: my-app-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-app-image:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: my-app-secret

---

# File: my-app-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: my-app-secret
  namespace: myapp
type: Opaque
data:
  DB_HOST: bXktcG9zdGdyZXMtc2VydmVyLnBvc3RncmVzLnN2Yy5jbHVzdGVyLmxvY2Fs
  DB_NAME: bXlhcHBkYg==
  DB_USER: bXlhcHB1c2Vy
  DB_PASSWORD: QXBwVXNlclBhc3MxMjM=
