apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name | lower}}-{{ .Values.global.deploymentType |lower}}-secret
  labels:
    {{- include "cloudbank.labels" . | nindent 4 }}
type: Opaque  
stringData:
