name: Build, Push Vector Image

on:
  push:
    branches: [ 'dev' ]
  workflow_dispatch:

jobs:
  build-image:
    name: Build and Push Image to Registry
    runs-on: ubuntu-latest
    environment: Production
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print the SHA
        run: echo "${GITHUB_SHA}"

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CONTAINER_REGISTRY_URL }}
          username: ${{ secrets.CONTAINER_REGISTRY_USER }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Build and push Docker image for app-service
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.CONTAINER_REGISTRY_URL }}/vector-replacement-backend/vector-backend:${{ github.sha }}

      - name: Deploy on Kubernetes
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        with:
          args: set image deployment/pride-group-api pride-group-api=${{ secrets.CONTAINER_REGISTRY_URL }}/vector-replacement-backend/vector-backend:${{ github.sha }} --namespace=pride-group

  notify-on-failure:
    name: Notify on Failure to Teams
    if: failure()
    runs-on: ubuntu-latest
    needs: build-image
    steps:
      - name: Send Teams notification
        run: |
          curl -H 'Content-Type: application/json' \
          -d '{
                "title": "🚨 GitHub CI/CD Failed",
                "text": "**Repository:** ${{ github.repository }}\n**Branch:** ${{ github.ref }}\n**Job:** ${{ github.job }}\n**Error:** Build or Deploy Failed.\n[View Logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"
              }' \
          ${{ secrets.TEAMS_WEBHOOK_URL }}
