kubectl get pods -n ingress-nginx
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mssql
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
      - name: mssql
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
        - containerPort: 1433
        env:
        - name: ACCEPT_EULA
          value: "Y"
        - name: SA_PASSWORD
          value: "YourStrong!Passw0rd"
        - name: MSSQL_PID
          value: "Developer"
---
apiVersion: v1
kind: Service
metadata:
  name: mssql
spec:
  selector:
    app: mssql
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
  type: ClusterIP
--------------------------------------------------------------------------------------------------------------------------------------------
kubectl apply -f mssql-deployment.yaml
--------------------------------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  "1433": "default/mssql:1433"
---------------------------------------------------------------------------------------------------------------------------------------------
kubectl apply -f tcp-services-configmap.yaml
---------------------------------------------------------------------------------------------------------------------------------------------
kubectl edit deployment ingress-nginx-controller -n ingress-nginx
- --tcp-services-configmap=ingress-nginx/tcp-services
---------------------------------------------------------------------------------------------------------------------------------------------
sqlcmd -S db.example.com,1433 -U SA -P 'YourStrong!Passw0rd'
---------------------------------------------------------------------------------------------------------------------------------------------
